name: CI/CD

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Nix
      uses: cachix/install-nix-action@v18
    - name: Rustfmt check
      run: nix develop -c cargo fmt --all --check
    - name: Run tests with substrate-std
      run: RUSTFLAGS="-D warnings" nix develop -c cargo test --workspace --features substrate-std
    - name: Run tests with ink-std
      run: RUSTFLAGS="-D warnings" nix develop -c cargo test --workspace --features ink-std
